#!/usr/bin/env node
/**
 * sync-abi.mjs — Hardhat 컴파일 산출물에서 ABI를 추출해
 * packages/contracts-abi/ 로 동기화.
 *
 * 산출물 2종을 같이 emit한다 (단일 진실원, 동일 내용, 다른 포맷):
 *   1. <Name>.json — { contractName, sourceName, abi }. engine(Python)이 로드.
 *   2. <Name>.ts   — `export const <NAME>_ABI = [...] as const`.
 *      frontend(wagmi v3 + viem)가 import. const-narrowed 타입이라야
 *      writeContract / readContract의 functionName·args 추론이 작동.
 *
 * 호출 위치 무관 (apps/contracts의 postcompile 훅 또는 root에서 직접).
 * 출력은 항상 ABI만 포함 (bytecode 제외).
 */

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const REPO_ROOT = resolve(__dirname, '..');

const SOURCES = [
  {
    name: 'DarkPoolEscrow',
    artifact: 'apps/contracts/artifacts/contracts/DarkPoolEscrow.sol/DarkPoolEscrow.json',
    out: 'packages/contracts-abi/DarkPoolEscrow.json',
  },
];

async function syncOne({ name, artifact, out }) {
  const artifactPath = resolve(REPO_ROOT, artifact);
  const outPath = resolve(REPO_ROOT, out);

  if (!existsSync(artifactPath)) {
    throw new Error(
      `[sync-abi] artifact not found: ${artifactPath}\n` +
        `먼저 'npm run compile'을 apps/contracts에서 실행하세요.`,
    );
  }

  const raw = JSON.parse(await readFile(artifactPath, 'utf8'));

  // 기대 필드 검증 — Hardhat artifacts 스키마가 깨지면 undefined 필드를
  // 그대로 직렬화해서 잘못된 산출물이 디스크에 써지는 사고 방지.
  if (
    typeof raw !== 'object' ||
    raw === null ||
    typeof raw.contractName !== 'string' ||
    typeof raw.sourceName !== 'string' ||
    !Array.isArray(raw.abi)
  ) {
    throw new Error(
      `[sync-abi] invalid artifact structure for ${name}: ` +
        `expected {contractName: string, sourceName: string, abi: array}, ` +
        `got keys=${Object.keys(raw || {}).join(',')} (${artifactPath})`,
    );
  }

  const minimal = {
    contractName: raw.contractName,
    sourceName: raw.sourceName,
    abi: raw.abi,
  };

  await mkdir(dirname(outPath), { recursive: true });
  await writeFile(outPath, JSON.stringify(minimal, null, 2) + '\n', 'utf8');

  // const-narrowed TS 산출물 — frontend(wagmi v3 + viem) 타입 안전성용.
  // JSON import는 string literal을 widening해서 functionName 추론을 깨므로
  // 별도 .ts 파일로 `as const` 단언을 박는다.
  const tsOutPath = outPath.replace(/\.json$/, '.ts');
  const constPrefix = name.replace(/[^A-Za-z0-9]/g, '').toUpperCase();
  const tsContent =
    `// AUTO-GENERATED by tools/sync-abi.mjs — DO NOT EDIT.\n` +
    `// 컨트랙트 변경 시 'cd apps/contracts && npm run compile' 로 재생성.\n` +
    `\n` +
    `export const ${constPrefix}_ABI = ${JSON.stringify(raw.abi, null, 2)} as const;\n`;
  await writeFile(tsOutPath, tsContent, 'utf8');

  const fnCount = raw.abi.filter((e) => e.type === 'function').length;
  const evCount = raw.abi.filter((e) => e.type === 'event').length;
  const tsRel = tsOutPath.replace(REPO_ROOT + '/', '');
  console.log(
    `[sync-abi] ${name}: ${fnCount} functions, ${evCount} events → ${out} + ${tsRel}`,
  );
}

async function main() {
  for (const src of SOURCES) {
    await syncOne(src);
  }
}

main().catch((err) => {
  console.error(err.message || err);
  process.exit(1);
});
